const HtmlWebPackPlugin = require("html-webpack-plugin");
const htmlPlugin = new HtmlWebPackPlugin({
	template: "./src/index.html",
	filename: "./index.html"
});

module.exports = {
	module: {
		rules: [
			{
				test: /\.js$/,
				exclude: /node_modules/,
				use: {
					loader: "babel-loader"
				}
			},
			{
				test: /\.css$/,
				use: [
						{
							loader: "style-loader"
						},
						{
							loader: require.resolve('css-loader'),
							options: {
								modules: true,
								importLoaders: 1,
								modules: {
									localIdentName: '[name]__[local]__[hash:base64:5]',
								},
								sourceMap: true,
								
								// Commenting this out as per guidance online
								// minimize: true
							}
						}
					]
			},
			{
				test: /\.(jpe?g|png|gif|woff|woff2|eot|ttf|svg)$/,
				loader: 'url-loader'

				/* Auto-generated by WebPack, but doesn't work
				use: [
					{
						loader: 'file-loader',
						options: {
							limit: 1000,
							name : './assets/img/[name].[ext]'
						}
					}
				]
				*/
			}
		]
	},
	plugins: [htmlPlugin],
};
	